### ISSUE TITLE
[BUG] app cannot access and create files

### ISSUE THREAD

**Issue by drakulaboy** [puutaro/CommandClick#1]
hi, i really want to try this app, the app close instantly, all Permissions granted, Android 10, no root
here is the full logcat of app
<details>
  <summary>Logcat</summary>
  
---------------------------- PROCESS STARTED (11771) for package com.puutaro.commandclick ----------------------------
2023-03-19 11:48:29.828 11771-11791 ActivityThread          com.puutaro.commandclick             I  Init compatible state: true
2023-03-19 11:48:29.829 11771-11791 HwFramewor...rtsFactory com.puutaro.commandclick             D  HwFrameworkSecurityPartsFactory in.
2023-03-19 11:48:29.829 11771-11791 HwFramewor...rtsFactory com.puutaro.commandclick             I  add HwFrameworkSecurityPartsFactory to memory.
2023-03-19 11:48:29.829 11771-11791 BehaviorCollectManager  com.puutaro.commandclick             E  Fail to acquire dataAnalyzerService...
2023-03-19 11:48:29.869 11771-11771 HwResourcesImpl         com.puutaro.commandclick             E  loadThemeColor : RuntimeException
2023-03-19 11:48:29.874 11771-11792 HwPartIawareFactory     com.puutaro.commandclick             I  add android.common.HwPartIawareFactoryImpl to memory.
2023-03-19 11:48:29.875 11771-11771 ApplicationLoaders      com.puutaro.commandclick             D  createClassLoader zip: /data/app/com.puutaro.commandclick-oGguKAlXLQcPzyQ4Pb4tnw==/base.apk librarySearchPath: /data/app/com.puutaro.commandclick-oGguKAlXLQcPzyQ4Pb4tnw==/lib/arm64:/data/app/com.puutaro.commandclick-oGguKAlXLQcPzyQ4Pb4tnw==/base.apk!/lib/arm64-v8a libraryPermittedPath: /data/user/0/com.puutaro.commandclick parent: java.lang.BootClassLoader@d8aafa7 targetSdkVersion: 33 isBundled: false classLoaderName: null sharedLibraries: null
2023-03-19 11:48:30.170 11771-11791 HwApiCacheMangerEx      com.puutaro.commandclick             I  apicache path=/storage/emulated/0 state=mounted key=com.puutaro.commandclick#11407#256
2023-03-19 11:48:30.170 11771-11791 HwApiCacheMangerEx      com.puutaro.commandclick             I  need clear apicache,because volumes changed,oldCnt=0 newCnt=1
2023-03-19 11:48:30.170 11771-11791 HwApiCacheMangerEx      com.puutaro.commandclick             I  apicache path=/storage/emulated/0 state=mounted key=com.puutaro.commandclick#11407#0
2023-03-19 11:48:30.171 11771-11791 HwApiCacheMangerEx      com.puutaro.commandclick             I  need clear apicache,because volumes changed,oldCnt=1 newCnt=1
2023-03-19 11:48:30.173 11771-11791 AwareBitmapCacher       com.puutaro.commandclick             I  init processName:com.puutaro.commandclick pid=11771 uid=11407
2023-03-19 11:48:30.173 11771-11805 AwareLog                com.puutaro.commandclick             E  AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@2cd6d8
2023-03-19 11:48:30.179 11771-11771 HwApiCacheMangerEx      com.puutaro.commandclick             I  apicache path=/storage/emulated/0 state=mounted key=com.puutaro.commandclick#11407#256
2023-03-19 11:48:30.179 11771-11771 HwApiCacheMangerEx      com.puutaro.commandclick             I  need clear apicache,because volumes changed,oldCnt=1 newCnt=1
2023-03-19 11:48:30.181 11771-11771 HwTypeface              com.puutaro.commandclick             I  updateFont: scale=0.95
2023-03-19 11:48:30.181 11771-11771 FontFamily              com.puutaro.commandclick             I  buildHwFonts: add Font {nativePtr=483243140704, path=/data/skin/fonts/DroidSansChinese.ttf, style=FontStyle { weight=400, slant=0}, ttcIndex=0, axes=, localeList=, buffer=java.nio.DirectByteBuffer[pos=0 lim=92876 cap=92876], isFontWeightVariable=false} to [Font {nativePtr=483243140704, path=/data/skin/fonts/DroidSansChinese.ttf, style=FontStyle { weight=400, slant=0}, ttcIndex=0, axes=, localeList=, buffer=java.nio.DirectByteBuffer[pos=0 lim=92876 cap=92876], isFontWeightVariable=false}]
2023-03-19 11:48:30.182 11771-11771 SystemFonts             com.puutaro.commandclick             D  isUsingHwThemeFonts: online invariable font existed
2023-03-19 11:48:30.182 11771-11771 ActivityThread          com.puutaro.commandclick             I  finishPreloaded preloadStatus 0
2023-03-19 11:48:30.182 11771-11771 RmeSchedManager         com.puutaro.commandclick             I  init Rme, version is: v1.0
2023-03-19 11:48:30.182 11771-11771 RtgSchedEvent           com.puutaro.commandclick             I  current pid:11771 AppType:-1
2023-03-19 11:48:30.182 11771-11771 RmeSchedManager         com.puutaro.commandclick             I  init Rme, version is: v1.0
2023-03-19 11:48:30.190 11771-11806 OpenGLRenderer          com.puutaro.commandclick             I  RenderThread: progress name = [com.puutaro.commandclick], viewCornerType = 0
2023-03-19 11:48:30.190 11771-11808 iGraphics               com.puutaro.commandclick             I  [0020080c] pn: com.puutaro.commandclick, p: 11771
2023-03-19 11:48:30.190 11771-11808 iGraphics               com.puutaro.commandclick             I  [0030080c] no spt app: com.puutaro.commandclick
2023-03-19 11:48:30.249 11771-11771 AppCompatDelegate       com.puutaro.commandclick             D  Checking for metadata for AppLocalesMetadataHolderService : Service not found
2023-03-19 11:48:30.256 11771-11771 ActivityThread          com.puutaro.commandclick             V  callActivityOnCreate
2023-03-19 11:48:30.267 11771-11771 ZipFileCache            com.puutaro.commandclick             D  initResDirInfo Completed!
2023-03-19 11:48:30.272 11771-11771 DecorView[]             com.puutaro.commandclick             I  pkgName:com.puutaro.commandclick old windowMode:0 new windoMode:1, isFixedSize:false
2023-03-19 11:48:30.283 11771-11771 OverScroll...timization com.puutaro.commandclick             I  start init SmartSlideOverScroller and get the overscroller config
2023-03-19 11:48:30.283 11771-11771 OverScroll...timization com.puutaro.commandclick             I  get the overscroller config
2023-03-19 11:48:30.297 11771-11771 ZipFileCache            com.puutaro.commandclick             D  initResDirInfo Completed!
2023-03-19 11:48:30.308 11771-11771 ro.commandclic          com.puutaro.commandclick             W  Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
2023-03-19 11:48:30.308 11771-11771 ro.commandclic          com.puutaro.commandclick             W  Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
2023-03-19 11:48:30.344 11771-11771 ActivityThread          com.puutaro.commandclick             D  add activity client record, r= ActivityRecord{c05e50c token=android.os.BinderProxy@45f7ca2 {com.puutaro.commandclick/com.puutaro.commandclick.activity.MainActivity}} token= android.os.BinderProxy@45f7ca2
2023-03-19 11:48:30.357 11771-11771 ApplicationLoaders      com.puutaro.commandclick             D  createClassLoader zip: /data/app/com.google.android.trichromelibrary_548115334-f9gPuyitUXV_7mFmdI8icw==/base.apk librarySearchPath: /data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/lib/arm64:/data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/base.apk!/lib/arm64-v8a:/data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/split_config.en.apk!/lib/arm64-v8a:/data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/split_config.ro.apk!/lib/arm64-v8a:/data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/split_config.ru.apk!/lib/arm64-v8a:/data/app/com.google.android.trichromelibrary_548115334-f9gPuyitUXV_7mFmdI8icw==/base.apk!/lib/arm64-v8a libraryPermittedPath:  parent: java.lang.BootClassLoader@d8aafa7 targetSdkVersion: 33 isBundled: false classLoaderName: null sharedLibraries: null
2023-03-19 11:48:30.359 11771-11771 ApplicationLoaders      com.puutaro.commandclick             D  createClassLoader zip: /data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/base.apk librarySearchPath: /data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/lib/arm64:/data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/base.apk!/lib/arm64-v8a:/data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/split_config.en.apk!/lib/arm64-v8a:/data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/split_config.ro.apk!/lib/arm64-v8a:/data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/split_config.ru.apk!/lib/arm64-v8a:/data/app/com.google.android.trichromelibrary_548115334-f9gPuyitUXV_7mFmdI8icw==/base.apk!/lib/arm64-v8a libraryPermittedPath:  parent: java.lang.BootClassLoader@d8aafa7 targetSdkVersion: 33 isBundled: false classLoaderName: null sharedLibraries: [dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.android.trichromelibrary_548115334-f9gPuyitUXV_7mFmdI8icw==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/lib/arm64, /data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/base.apk!/lib/arm64-v8a, /data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/split_config.ro.apk!/lib/arm64-v8a, /data/app/com.google.android.webview-o6nM1w2Mo5AEYjJWizCUVQ==/split_config.ru.apk!/lib/arm64-v8a, /data/app/com.google.android.trichromelibrary_548115334-f9gPuyitUXV_7mFmdI8icw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]]]
2023-03-19 11:48:30.366 11771-11771 WebViewFactory          com.puutaro.commandclick             I  Loading com.google.android.webview version 110.0.5481.153 (code 548115334)
2023-03-19 11:48:30.370 11771-11771 linker                  com.puutaro.commandclick             W  Warning: "/data/app/com.google.android.trichromelibrary_548115334-f9gPuyitUXV_7mFmdI8icw==/base.apk!/lib/arm64-v8a/libmonochrome_64.so" unused DT entry: unknown processor-specific (type 0x70000001 arg 0x0) (ignoring)
2023-03-19 11:48:30.379 11771-11771 ro.commandclic          com.puutaro.commandclick             W  Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
2023-03-19 11:48:30.379 11771-11771 ro.commandclic          com.puutaro.commandclick             W  Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
2023-03-19 11:48:30.379 11771-11771 ro.commandclic          com.puutaro.commandclick             W  Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
2023-03-19 11:48:30.379 11771-11771 ro.commandclic          com.puutaro.commandclick             W  Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
2023-03-19 11:48:30.379 11771-11771 ro.commandclic          com.puutaro.commandclick             W  Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
2023-03-19 11:48:30.381 11771-11771 cr_WVCFactoryProvider   com.puutaro.commandclick             I  Loaded version=110.0.5481.153 minSdkVersion=29 isBundle=true multiprocess=true packageId=3
2023-03-19 11:48:30.400 11771-11771 cr_LibraryLoader        com.puutaro.commandclick             I  Successfully loaded native library
2023-03-19 11:48:30.401 11771-11771 cr_CachingUmaRecorder   com.puutaro.commandclick             I  Flushed 8 samples from 8 histograms.
2023-03-19 11:48:30.426 11771-11824 chromium                com.puutaro.commandclick             W  [WARNING:dns_config_service_android.cc(115)] Failed to read DnsConfig.
2023-03-19 11:48:30.492 11771-11771 writeFiles              com.puutaro.commandclick             E  cannot write file: android.system.ErrnoException: open failed: ENOENT (No such file or directory), /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_src_image_anchor.js: open failed: ENOENT (No such file or directory), [Ljava.lang.StackTraceElement;@1ce12e, /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_src_image_anchor.js
2023-03-19 11:48:30.493 11771-11771 writeFiles              com.puutaro.commandclick             E  cannot write file: android.system.ErrnoException: open failed: ENOENT (No such file or directory), /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_src_image_anchor.js: open failed: ENOENT (No such file or directory), [Ljava.lang.StackTraceElement;@7c14cf, /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_src_image_anchor.js
2023-03-19 11:48:30.494 11771-11771 writeFiles              com.puutaro.commandclick             E  cannot write file: android.system.ErrnoException: open failed: ENOENT (No such file or directory), /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_src_anchor.js: open failed: ENOENT (No such file or directory), [Ljava.lang.StackTraceElement;@4432565, /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_src_anchor.js
2023-03-19 11:48:30.495 11771-11771 writeFiles              com.puutaro.commandclick             E  cannot write file: android.system.ErrnoException: open failed: ENOENT (No such file or directory), /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_src_anchor.js: open failed: ENOENT (No such file or directory), [Ljava.lang.StackTraceElement;@719e23a, /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_src_anchor.js
2023-03-19 11:48:30.496 11771-11771 writeFiles              com.puutaro.commandclick             E  cannot write file: android.system.ErrnoException: open failed: ENOENT (No such file or directory), /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_image_anchor.js: open failed: ENOENT (No such file or directory), [Ljava.lang.StackTraceElement;@c44c448, /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_image_anchor.js
2023-03-19 11:48:30.496 11771-11771 writeFiles              com.puutaro.commandclick             E  cannot write file: android.system.ErrnoException: open failed: ENOENT (No such file or directory), /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_image_anchor.js: open failed: ENOENT (No such file or directory), [Ljava.lang.StackTraceElement;@4c5b2e1, /storage/emulated/0/Documents/cmdclick/AppDir/default/system/hit/long_press_image_anchor.js
2023-03-19 11:48:30.559 11771-11771 HwResourcesImpl         com.puutaro.commandclick             E  loadThemeColor : RuntimeException
2023-03-19 11:48:30.571 11771-11771 createFiles             com.puutaro.commandclick             E  cannot make file: null, No such file or directory, [Ljava.lang.StackTraceElement;@a1958fa, /storage/emulated/0/Documents/cmdclick/conf/AppHistoryDir/default__.js
2023-03-19 11:48:30.594 11771-11771 BlockMonitor            com.puutaro.commandclick             I  dispatchingThrewException In MainThread
2023-03-19 11:48:30.594 11771-11771 AndroidRuntime          com.puutaro.commandclick             D  Shutting down VM
2023-03-19 11:48:30.594 11771-11771 QarthLog                com.puutaro.commandclick             I  [PatchStore] createDisableExceptionQarthFile
2023-03-19 11:48:30.595 11771-11771 QarthLog                com.puutaro.commandclick             I  [PatchStore] create disable file for com.puutaro.commandclick uid is 11407
2023-03-19 11:48:30.597 11771-11771 AndroidRuntime          com.puutaro.commandclick             E  FATAL EXCEPTION: main
                                                                                                    Process: com.puutaro.commandclick, PID: 11771
                                                                                                    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
                                                                                                    Caused by: java.io.FileNotFoundException: /storage/emulated/0/Documents/cmdclick/conf/AppDirAdmin/default.js: open failed: ENOENT (No such file or directory)
                                                                                                        at libcore.io.IoBridge.open(IoBridge.java:496)
                                                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
                                                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
                                                                                                        at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
                                                                                                        at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134)
                                                                                                        at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134)
                                                                                                        at com.puutaro.commandclick.common.variable.CommandClickShellScript$Companion.makeAppDirAdminFile(CommandClickShellScript.kt:389)
                                                                                                        at com.puutaro.commandclick.fragment.CommandIndexFragment.onViewCreated(CommandIndexFragment.kt:75)
                                                                                                        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
                                                                                                        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
                                                                                                        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
                                                                                                        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899)
                                                                                                        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817)
                                                                                                        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760)
                                                                                                        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985)
                                                                                                        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
                                                                                                        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
                                                                                                        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
                                                                                                        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
                                                                                                        at com.puutaro.commandclick.activity.MainActivity.onStart(MainActivity.kt:110)
                                                                                                        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447)
                                                                                                        at android.app.Activity.performStart(Activity.java:8237)
                                                                                                        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4084)
                                                                                                        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
                                                                                                        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
                                                                                                        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
                                                                                                        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105)
                                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                        at android.os.Looper.loop(Looper.java:219)
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:8668)
                                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
                                                                                                    Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                                                        at libcore.io.Linux.open(Native Method)
                                                                                                        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
                                                                                                        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
                                                                                                        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
                                                                                                        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8464)
                                                                                                        at libcore.io.IoBridge.open(IoBridge.java:482)
                                                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:235) 
                                                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:186) 
                                                                                                        at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108) 
                                                                                                        at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134) 
                                                                                                        at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134) 
                                                                                                        at com.puutaro.commandclick.common.variable.CommandClickShellScript$Companion.makeAppDirAdminFile(CommandClickShellScript.kt:389) 
                                                                                                        at com.puutaro.commandclick.fragment.CommandIndexFragment.onViewCreated(CommandIndexFragment.kt:75) 
                                                                                                        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128) 
                                                                                                        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552) 
                                                                                                        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261) 
                                                                                                        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1899) 
                                                                                                        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1817) 
                                                                                                        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1760) 
                                                                                                        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2985) 
                                                                                                        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895) 
                                                                                                        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263) 
                                                                                                        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351) 
                                                                                                        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251) 
                                                                                                        at com.puutaro.commandclick.activity.MainActivity.onStart(MainActivity.kt:110) 
                                                                                                        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1447) 
                                                                                                        at android.app.Activity.performStart(Activity.java:8237) 
                                                                                                        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4084) 
                                                                                                        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235) 
                                                                                                        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215) 
                                                                                                        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187) 
                                                                                                        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:105) 
                                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613) 
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                                                        at android.os.Looper.loop(Looper.java:219) 
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:8668) 
                                                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) 
2023-03-19 11:48:30.605 11771-11771 Process                 com.puutaro.commandclick             I  Sending signal. PID: 11771 SIG: 9
---------------------------- PROCESS ENDED (11771) for package com.puutaro.commandclick ----------------------------

</details>

**Comment by puutaro** [comment]
Your issue suport 906e89cf241289d270ff6d63ecc1fefa49814805.
Please check [v0.0.13](https://github.com/puutaro/CommandClick/releases)

**Comment by drakulaboy** [comment]
@puutaro oh, tank you very much, got it eunning, going to explore it.
